name: Build and Test CleanArchitecture-Showcase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore ./CleanArchitecture-Showcase.sln
      - name: Build
        run: dotnet build ./CleanArchitecture-Showcase.sln --no-restore
      - name: Test
        run: dotnet test ./tests/CleanArchShowcase.Tests/CleanArchShowcase.Tests.csproj --no-build --verbosity normal 